services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: explorewithme
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  main-db:
    image: postgres:16.1
    container_name: main-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: explorewithme
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  stats-server:
    build: ./ewm-stats-service/stats-server
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/explorewithme
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  ewm-service:
    build: ./ewm-main-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - main-db
    environment:
      STATS_SERVER_URL: http://stats-server:9090
      SPRING_DATASOURCE_URL: jdbc:postgresql://main-db:5432/explorewithme
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
