server.port=8080
spring.application.name=ewm-main-service
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/explorewithme}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
stats-server.url=${STATS_SERVER_URL:http://localhost:9090}